### ISSUE TITLE
WARNING in Circular dependency detected 

### ISSUE THREAD

**Issue by CedricDumont** [SoCreate/angular-playground#48]
step to reproduce,
I created a simple angular Cli (1.4.2) project and generated a **note** component.
configured as explained in the doc.
added a *note.component.sandbox.ts* file with the following

```
import { sandboxOf } from 'angular-playground';
import { NoteComponent } from './note.component';
 
export default sandboxOf(NoteComponent)
  .add('simple', {
    template: `<app-note></app-note>`
  });   
```

when running 
*yarn playground*

in the console, I have
```
WARNING in Circular dependency detected:
src\app\note\note.component.sandbox.ts -> node_modules\angular-playground\dist\index.js -> node_modules\angular-playgrou
nd\dist\src\app\playground.module.js -> node_modules\angular-playground\dist\src\app\playground-common.module.js -> node
_modules\angular-playground\dist\src\app\load-sandboxes.js -> src\sandboxes.ts -> src\app\note\note.component.sandbox.ts
```
and when browsing  to http://localhost:4201/

the page displays:
> The app has 1 sandboxed component loaded.
> Pick sandboxed components:  ctrl + o or f1

When I hit F1 I got the dialog,
but when typing "simp..." the dialog does not autocomplete and no component is displayed.

is it working with angular cli 1.4.2 and angular 4 ?
use of 
version :"angular-playground": "^1.7.1"*

**Comment by CedricDumont** [comment]
for more info if ever needed
the generated *sandboxes.ts*

```javascript
import { default as s1 } from './app/note/note.component.sandbox';
export let sandboxes: any[] = [];
sandboxes.push(s1.serialize('NoteComponent'));
```

**Comment by lurock** [comment]
Try using the 2.x version just released and see if you are still having issues.

**Comment by CedricDumont** [comment]
I have updated, now I have this error showing up from ng serve:
ERROR in ..../src/sandboxes.ts (7,8): Expression expected.
ERROR in /.../src/sandboxes.ts (7,14): Unreachable code detected.
ERROR in /...../src/sandboxes.ts (7,70): Property 'then' does not exist on type '"./app/command-input/command-input.component.sandbox"'.

I just created a new fresh project (ng client project), then followed instruction on website and just started:
yarn run playground.

**Comment by lurock** [comment]
This error is caused because the new version of Angular Playground 2.0.0 or higher requires you use Typescript 2.4 or higher.  Change your devDependencies for typescript to be version 2.4.x or higher and this should resolve your issue.  We are updating or docs and will have a requirements page up on the web shortly.

**Comment by perseus086** [comment]
After upgrading to typescript 2.4.2 I got the following error:

`.../map/src/sandboxes.ts (7,8): Dynamic import cannot be used when targeting ECMAScript 2015 modules.`

How can I solve this issue?

**Comment by CedricDumont** [comment]
I also upgraded to typescript 2.4.2 and using the very last angular cli and still same error as @perseus086

**Comment by mgmarlow** [comment]
@perseus086 @CedricDumont Can you double-check that your `tsconfig.app.json` has an entry for `"module": "esnext"`?

Example:
```
{ 
  "extends": "../tsconfig.json", 
  "compilerOptions": { 
    "outDir": "../out-tsc/app", 
    "baseUrl": "./", 
    "module": "esnext", 
    "types": [] }, 
    "exclude": [ 
      "test.ts", 
      "**/*.spec.ts" 
    ] 
  }
}
```

**Comment by perseus086** [comment]
Adding `"module": "esnext"` fixed the issue.

Thank you @mgmarlow 😃
